### ISSUE TITLE
Example queries

### ISSUE THREAD

**Issue by leledumbo** [redound/phalcon-graphql-boilerplate#1]
Hello,

it's a nice coincidence that I found this newly born project when we have a need to implement GraphQL on top of Phalcon. Looking at your commits, I assume a change from 0.1.0 to 1.0.0 marks its usability. So far, I've been able to install only, but querying, for instance `{ user { id }}` results in:

```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field \"user\" on type \"Query\".",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ]
    }
  ]
}
```
apology for my narrow knowledge of GraphQL. I just need a few sample working queries.

**Comment by bblok11** [comment]
Hi,

The root object on the Query type is named viewer, on viewer you can find all query fields. You can use a tool like https://github.com/redound/graphql-ide to explore the GraphQL schema that the boilerplate creates. You could write the following query:

`query {
  viewer {
    allProjects {
      items {
        title
      }
    }
  }
}`

**Comment by leledumbo** [comment]
Alright, that rocks. I need to dig in deeper as you use factory pattern everywhere. That IDE will surely come in handy. Thanks.
